### An example OOP Class: Pandas.DataFrame

##### Pandas.DataFrame is an example of a Class

In [8]:
import pandas as pd

#### Instantiation

In [9]:
df = pd.read_csv("data/titanic.csv")

In [10]:
df

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [11]:
type(df)

pandas.DataFrame

#### Attributes

In [12]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='str')

In [13]:
df.shape

(891, 9)

#### Methods

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    str
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    str
 8   deck      203 non-null    str
dtypes: float64(2), int64(4), str(3)
memory usage: 62.8 KB

In [15]:
df.sort_values(by="age", ascending=False)

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
630         1       1    male  80.0      0      0  30.0000        S    A
851         0       3    male  74.0      0      0   7.7750        S  NaN
493         0       1    male  71.0      0      0  49.5042        C  NaN
96          0       1    male  71.0      0      0  34.6542        C    A
116         0       3    male  70.5      0      0   7.7500        Q  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
859         0       3    male   NaN      0      0   7.2292        C  NaN
863         0       3  female   NaN      8      2  69.5500        S  NaN
868         0       3    male   NaN      0      0   9.5000        S  NaN
878         0       3    male   NaN      0      0   7.8958        S  NaN
888         0       3  female   NaN      1      2  23.4500        S  NaN

[891 rows x 9 columns]