<center><u><H2>OPERATIONS WITH PANDAS</H2><u/></center>

In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame({'col1':[1,2,3,14,25],'col2':[44,44,66,54,52],'col3':['ab','de','gc','xc','we']})
df.head(3)

   col1  col2 col3
0     1    44   ab
1     2    44   de
2     3    66   gc

In [3]:
df['col2'].sum()

271

In [4]:
(df['col2']==44).sum()

1

In [5]:
df['col2'].count()

5

In [8]:
df['col2'].value_counts()

44    2
54    1
52    1
66    1
Name: col2, dtype: int64

In [ ]:
df['col2'].values

In [ ]:
a = df.columns.values
b = sorted(a)
b

In [ ]:
# sorting by column
df.sort_values(by='col2')

In [ ]:
df1 = pd.DataFrame([[np.nan, 10, np.nan, 5], [13, 44, np.nan, 11],
                    [np.nan, np.nan, np.nan, 15]],
                   columns=list('ABCD'))
df1

In [ ]:
#boolean
df1.isnull()

In [ ]:
#dropping non values
df1.dropna(inplace=True)
df1

In [10]:
#filling non values
df.loc[6]=[np.nan,2,np.nan]
df.fillna('value',inplace=True)
df

    col1  col2   col3
0      1  44.0     ab
1      2  44.0     de
2      3  66.0     gc
3     14  54.0     xc
4     25  52.0     we
6  value   2.0  value

In [ ]:
#Sort by index
df.sort_index(ascending=False,inplace=True)
df

### STRING OPERATIONS:

In [12]:
#extracting strings:
df['col1'].str.extract('(\w+)', expand=False)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
6    value
Name: col1, dtype: object

### Filtering:

In [ ]:
df[df['col3']=='ab']

### Uppercase/Lowercase:

In [1]:
df['col3'].str.upper()#lower()

NameError: name 'df' is not defined

In [ ]:
df['col3'].str[0]

### Lenght of the string:

In [ ]:
df['col3'].str.len()

### Split:

In [ ]:
df['col3'].str.split('c')

### Replace:

In [ ]:
df['col3'].str.replace(' ','c')

### Contains:

In [ ]:
c=df['col3'].str.contains('c')
c

### ONE HOT ENCODING:

In [ ]:
#The output will be a sparse matrix where each column corresponds to one possible value of one feature
dfhot = pd.DataFrame({'gender':['male','female','male','female','male'],'age_range':['young','adult','senior','young','adult']})
dfhot

In [ ]:
data_dummies = pd.get_dummies(dfhot)
data_dummies

## References:

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html

https://pandas.pydata.org/pandas-docs/stable/text.html