<center><u><H1>Pandas: Data Structures and Properties</H1></u></center>

### Pandas Library has the following main data structures:

1.Series

2.DataFrames

<u><H2>SERIES:</H2></u>

In [2]:
import pandas as pd
import numpy as np

In [ ]:
pd.Series(np.random.randn(5))

### The index of the series can be customized with index values(letters or numbers):

In [ ]:
pd.Series(np.random.randn(5), index=[1,2,3,4,5])

### We also can use a Python dict:

In [ ]:
d = {'A': 1, 'B': 13, 'C': 'zyx'}
pd.Series(d)

<u><H2>DataFrame:</H2><u>

<b>DataFrame is a 2D data structure with columns of different datatypes and rows are named index. It can be formed from the following data structures:</b>
1. Numpy array
2. Lists
3. Dicts
4. Series
5. 2D numpy array

In [4]:
#using dict of series
d = {'column_1': pd.Series([10,12,13]),
    'column_2': pd.Series(['abc',17,'amc'])}
df = pd.DataFrame(d)
df

   column_1 column_2
0        10      abc
1        12       17
2        13      amc

In [3]:
#using dict of lists
d = {'column_1': [21,12,3],
    'column_2': ['ab','A','tyz'],
    'column_3': [1,3,6]}
df = pd.DataFrame(d)
df

   column_1 column_2  column_3
0        21       ab         1
1        12        A         3
2         3      tyz         6

### Selection and Indexing:

In [ ]:
# selecting a column
df['column_3']

In [ ]:
# selecting more than one column
df[['column_1','column_3']]

### <u>loc and iloc:</u>
#### -loc works on labels in the index.
#### -iloc works on the positions in the index (so it only takes integers).

In [ ]:
#selecting rows
df.loc[1]

In [ ]:
df.iloc[0]

In [ ]:
df.set_index('column_2', inplace=True)
df

In [ ]:
df.iloc[0]

In [ ]:
df.loc['ab']

In [ ]:
type(df['column_1'])

### Inserting new column

In [ ]:
df['new'] = df['column_1'] + df['column_3']
df

### Deleting a column

In [ ]:
df.drop('new',axis=1,inplace=True) # use inplace to make changes permanent
df

### Return item and drop it from dataframe

In [ ]:
df['new'] = df['column_1'] + df['column_3']
new = df.pop('new')

In [ ]:
df

In [ ]:
new

### Selecting a subset of the dataframe with rows and columns

In [ ]:
df.loc['A','column_1']

In [ ]:
#reset index
df.reset_index(inplace=True)
df

In [ ]:
df.loc[[0,2],['column_2','column_3']]

### Selection by condition:

In [ ]:
df[df['column_1']>10][['column_2','column_3']]

In [ ]:
df[(df['column_1']>10) & (df['column_3'] > 1)]

### Index properties:

In [ ]:
#Array of index values
df.index.values

In [ ]:
#Using the split function of strings to have a list of items
a = 'C t 5'.split()

In [ ]:
#Inserting new column since list values
df['column_4'] = a
df

In [ ]:
#Inserting new row
df.loc[3]=[0.6,43,'xy','v']
df

## References:

https://pandas.pydata.org/pandas-docs/stable/dsintro.html

https://pandas.pydata.org/pandas-docs/stable/basics.html